### PR TITLE
Bump Bulma version

### LINKED ISSUE #65: Use latest version of bulma
That's it.

### PR DESCRIPTION
**Pull request by jeanleonino**
Fixes #65

### CODE REVIEW

**Comment by alexdiliberto** [comment]
Hey @jeanleonino Thank you for your PR! Unfortunately right now we cannot make this update to latest version. We use this CSS framework as the base layer for a large production application and going from [Bulma v0.1.2 to v0.4.3](https://github.com/jgthms/bulma/compare/0.1.2...0.4.3) would break our app visually and allow a tougher gradual upgrade process.

The idea is that we slowly upgrade our way to latest or 0.4.3 while addressing visual inconsistencies along the way. We would welcome any other PRs to help us gradually upgrade like tests, etc.

For some historical context for what I'm talking about you can see the following:
https://github.com/open-tux/ember-bulma/issues/63
https://github.com/open-tux/ember-bulma/pull/62#issue-234373675

I'll let @crodriguez1a and @jbailey4 chime in here if they wan't to provide any other feedback

**Comment by jbailey4** [comment]
@alexdiliberto Maybe we should take this Bulma update and release an alpha or canary version. That way others can get this update, test it out, and submit fixes. The same would apply to our prod app, we can bump to the alpha release and test it out.

/cc @crodriguez1a

**Comment by crodriguez1a** [comment]
I think @jbailey4 idea is an good one. A canary or an alpha would be a good way to preview Bulma's updates. @jeanleonino Would you want to take that on, and maybe add a few tests along the way?

cc/ @alexdiliberto @jeanleonino

**Comment by jbailey4** [comment]
@jeanleonino We also need to update the default blueprint, to include the latest bulma version when the addon is installed -> https://github.com/open-tux/ember-bulma/blob/master/blueprints/ember-bulma/index.js#L16

**Comment by jlegrone** [comment]
Thanks for raising this @jeanleonino!  I'm closing in favor of https://github.com/open-tux/ember-bulma/pull/71 (bumps to latest bulma version); a new ember-bulma version should be released shortly.

**Comment by jlegrone** [comment]
@jeanleonino this is released in 0.3.0.

**Pull request closed without merging**
