### PR TITLE
Ember CLI v2.12 -> v2.13

### PR DESCRIPTION
**Pull request by alexdiliberto**
Update to CLI v2.13 and remove all console warnings

Additionally, Locking bulma at 0.1.2 as well -- I was seeing some visual diffs when updating to latest (@jbailey4) -- See https://github.com/open-tux/ember-bulma/issues/63

### CODE REVIEW

**Comment by crodriguez1a** [comment]
@alexdiliberto 👍 You mind also committing you `.gitignore` with `/yarn-error.log` added as well?

**Comment by alexdiliberto** [comment]
ping @jbailey4

**Comment by alexdiliberto** [comment]
@jbailey4 We have 2 license files here for some reason, I'm deleting the one that's not auto generated by CLI

**Comment by jbailey4** [comment]
@alexdiliberto 👍

**Pull request merged**
